TES3:
   subrecords:
      HEDR:
         data:
         -  type: float
            name: version
         -  type: int
            name: format
            enum:
               0: esp
               1: esm
         -  type: string
            length: 32
            name: author
         -  type: string
            length: 256
            name: description
         -  type: int
            name: records
      MAST:
         data:
         -  type: string
            output:
            -  push: masters
            -  set:
               - masters
               - name
      DATA:
         data:
         -  type: long
            name:
            - masters
            - length
   output:
   -  yaml: header.yaml
SCPT:
   subrecords:
      SCHD:
         data:
         -  type: string
            length: 32
            name: id
         -  type: int
            name: shorts
         -  type: int
            name: longs
         -  type: int
            name: floats
         -  type: int
            name: data
         -  type: int
            name: table
      SCVR:
         data:
         -  type: binary
            name: variables
      SCDT:
         data:
         -  type: hex
            name: hex
      SCTX:
         data:
         -  type: string
            name: src
      DELE:
         data:
         -  type: marker
            name: deleted
            value: true
   output:
   -  raw:
      - scripts
      -  var: id
      - script.var
      value: variables
   -  delete: variables
   -  raw:
      - scripts
      -  var: id
      - script.hex
      value: hex
   -  delete: hex
   -  raw:
      - scripts
      -  var: id
      - script.src
      value: src
   -  delete: src
   -  yaml:
      - scripts
      -  var: id
      - metadata.yaml